---
title: "Untitled"
author: "yangqingxin"
date: "2024/1/8"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#1 loading package and data
##1.1. package
```{r}
library(Seurat)
library(Matrix)
library(magrittr)
library(ggplot2)
library(data.table)
library(dplyr)
library(rtracklayer)
library(RColorBrewer)
library(scmap)
```
##1.3. seurat data
```{r}
Pbsce <- readRDS("../Data/01_02_Pb_seurat.Rds")
Pfsce <- readRDS("../Data/02_02_Pf_seurat.Rds")
```
##1.4. Orth data
```{r}
Orth <- read.xlsx("../Data/02_Gene_Orth_Data.xlsx",sheetIndex = 1)
Orth %<>% as.data.table()
```

#2. Select conserved gene
```{r}
#PBANKA
PBANKA <- Orth$berghei
PBANKA <- gsub("_","-",PBANKA)
PBANKA <- PBANKA[which(PBANKA%in%rownames(Pbsce))]

#PF3D7
PF3D7  <- Orth$falciparum
PF3D7 <- gsub("_","-",PF3D7)
PF3D7 <- PF3D7[which(PF3D7%in%rownames(Pfsce))]
PF3D7_bp <- Orth$berghei[which(gsub("_","-",Orth$falciparum)%in%PF3D7)]
PF3D7_bp <- gsub("_","-",PF3D7_bp)

#Final
##PBANKA
Final_Pb <- intersect(PF3D7_bp,PBANKA)
##PF3D7
Final_Pf3D7 <- Orth$falciparum[which(gsub("_","-",Orth$berghei)%in%Final_Pb)]
Final_Pf3D7 <- gsub("_", "-", Final_Pf3D7)

#check
identical(Orth$berghei%in%gsub("-","_",Final_Pb),Orth$falciparum%in%gsub("-","_",Final_Pf3D7))
rm(PBANKA,PF3D7,PF3D7_bp)

#Conclusion
DF <- data.table(
  PB_Name = Final_Pb,
  PF_Name = Final_Pf3D7
)
```

#3. Ring Stage
##3.1. 
```{r}
Pbsce_ring <- subset(Pbsce,Cluster%in%c("Early ring","Late ring"))
Pfsce_ring <- subset(Pfsce,STAGE_LR%in%c("ring"))
```
##3.2. 
```{r}
#
Pbsce_ring <- subset(Pbsce_ring,features = DF$PB_Name)
Pbsce_ring  <-  as.SingleCellExperiment(Pbsce_ring)
#
pf_couts <- Pfsce_ring@assays$RNA@counts[DF$PF_Name,]
rownames(pf_couts) <- DF$PB_Name
pf_logcounts <- Pfsce_ring@assays$RNA@data[DF$PF_Name,]
rownames(pf_logcounts) <- DF$PB_Name
#
Pfsce_ring <- SingleCellExperiment(assays=list(counts=pf_couts, logcounts=pf_logcounts),
                                          reducedDims=SimpleList(PCA=Pfsce_ring@reductions$pca, uMAP=Pfsce_ring@reductions$umap))

```
##3.3. 
```{r}
rowData(Pbsce_ring)$feature_symbol <- rownames(Pbsce_ring) 
Pbsce_ring  <- scmap::selectFeatures(Pbsce_ring , n_features = 3000,suppress_plot = FALSE)
Pbsce_ring <- indexCluster(Pbsce_ring,cluster_col = "Cluster")
```
##3.4. 
```{r}
rowData(Pfsce_ring)$feature_symbol <- rownames(Pfsce_ring) 
scmapCluster_results_ring <- scmapCluster(     
        projection = Pfsce_ring,      
        index_list = list(         
            pb = metadata(Pbsce_ring)$scmap_cluster_index     
        ),threshold = 0
 )
scmapCluster_results_ring$combined_labs%>%table()
```
##3.5. 
```{r}
Pfsce_ring <- subset(Pfsce,STAGE_LR%in%c("ring"))
Pfsce_ring$Scmap <- scmapCluster_results_ring$combined_labs
UMAPPlot(Pfsce_ring,group.by="Scmap")
```

#4. Troph stage
##4.1. 
```{r}
Pbsce_troph <-  subset(Pbsce,Cluster%in%c("Early troph","Mid troph","Late troph"))
Pfsce_troph <- subset(Pfsce,STAGE_LR%in%c("trophozoite"))
```
##4.2. 
```{r}
Pbsce_troph <- subset(Pbsce_troph,features = DF$PB_Name)
Pbsce_troph  <-  as.SingleCellExperiment(Pbsce_troph)
pf_couts <- Pfsce_troph@assays$RNA@counts[DF$PF_Name,]
rownames(pf_couts) <- DF$PB_Name
pf_logcounts <- Pfsce_troph@assays$RNA@data[DF$PF_Name,]
rownames(pf_logcounts) <- DF$PB_Name
##
Pfsce_troph <- SingleCellExperiment(assays=list(counts=pf_couts, logcounts=pf_logcounts),
                                          reducedDims=SimpleList(PCA=Pfsce_troph@reductions$pca, uMAP=Pfsce_troph@reductions$umap))

```
##4.3. 
```{r}
rowData(Pbsce_troph)$feature_symbol <- rownames(Pbsce_troph) 
Pbsce_troph  <- scmap::selectFeatures(Pbsce_troph , n_features = 3000,suppress_plot = FALSE)
Pbsce_troph <- indexCluster(Pbsce_troph,cluster_col = "Cluster")
```
##4.4. 
```{r}
rowData(Pfsce_troph)$feature_symbol <- rownames(Pfsce_troph) 
scmapCluster_results_troph <- scmapCluster(     
        projection = Pfsce_troph,      
        index_list = list(         
            pb = metadata(Pbsce_troph)$scmap_cluster_index     
        ),threshold = 0
 )
scmapCluster_results_troph$combined_labs%>%table()
```
##4.5. 
```{r}
Pfsce_troph <- subset(Pfsce,STAGE_LR%in%c("trophozoite"))
Pfsce_troph$Scmap <- scmapCluster_results_troph$combined_labs
UMAPPlot(Pfsce_troph,group.by="Scmap")
```

#5. schi
##5.1. 
```{r}
Pbsce_schi <- subset(Pbsce,Cluster%in%c("Early schi","Mid schi","Late schi"))
Pfsce_schi <-  subset(Pfsce,STAGE_LR%in%c("schizont"))
```
##5.2. 
```{r}
Pbsce_schi <- subset(Pbsce_schi,features = DF$PB_Name)
Pbsce_schi  <-  as.SingleCellExperiment(Pbsce_schi)
pf_couts <- Pfsce_schi@assays$RNA@counts[DF$PF_Name,]
rownames(pf_couts) <- DF$PB_Name
pf_logcounts <- Pfsce_schi@assays$RNA@data[DF$PF_Name,]
rownames(pf_logcounts) <- DF$PB_Name
##
Pfsce_schi <- SingleCellExperiment(assays=list(counts=pf_couts, logcounts=pf_logcounts),
                                          reducedDims=SimpleList(PCA=Pfsce_schi@reductions$pca, uMAP=Pfsce_schi@reductions$umap))

```
##5.3. 
```{r}
rowData(Pbsce_schi)$feature_symbol <- rownames(Pbsce_schi) 
Pbsce_schi  <- scmap::selectFeatures(Pbsce_schi , n_features = 3000,suppress_plot = FALSE)
Pbsce_schi <- indexCluster(Pbsce_schi,cluster_col = "Cluster")
```
##5.4.
```{r}
rowData(Pfsce_schi)$feature_symbol <- rownames(Pfsce_schi) 
scmapCluster_results_schi <- scmapCluster(     
        projection = Pfsce_schi,      
        index_list = list(         
            pb = metadata(Pbsce_schi)$scmap_cluster_index     
        ),threshold = 0
 )
scmapCluster_results_schi$combined_labs%>%table()
```
##5.5.
```{r}
Pfsce_schi <-  subset(Pfsce,STAGE_LR%in%c("schizont"))
Pfsce_schi$Scmap <- scmapCluster_results_schi$combined_labs
UMAPPlot(Pfsce_schi,group.by="Scmap")
```

#6. Conclusion
##6.1. 
```{r}
Data <- do.call(rbind,list(Pfsce_ring@meta.data,Pfsce_troph@meta.data,Pfsce_schi@meta.data))
Data$Scmap%<>%as.character()
#
Pfsce$Scmap <- Data[colnames(Pfsce),]$Scmap
```
##6.2. 
```{r,fig.width=6.5,fig.height=5}
Pfsce$Scmap <- factor(Pfsce$Scmap ,
                                 levels = c("Early ring","Late ring",
                                            "Early troph","Mid troph","Late troph",
                                            "Early schi","Mid schi","Late schi"))
UMAPPlot(Pfsce,group.by="Scmap")+scale_color_brewer(palette = "Set1")+scale_x_reverse()+scale_y_reverse()
```


