---
title: "Untitled"
author: "yangqingxin"
date: "2024/1/8"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


#1 loading package and data
##1.1 package
```{r}
library(Seurat)
library(Matrix)
library(magrittr)
library(ggplot2)
library(data.table)
library(dplyr)
library(rtracklayer)
library(xlsx)
library(ComplexHeatmap)
library(circlize)
library(grid)
```
##1.2. data
```{r}
Pbsce <- readRDS("../Data/01_01_Pb_seurat.Rds")
Pfsce <- readRDS("../Data/01_02_Pf_seurat.Rds")
Lipid_gene <- read.xlsx("../Data/03_LipidGene.xlsx",sheetIndex = 1)%>%as.data.table()
```

#2. 
##2.1. 
```{r}
Lipid_gene <- Lipid_gene[which(!is.na(Lipid_gene$P..berghei.ID)),]
Lipid_gene$GeneName[which(is.na(Lipid_gene$GeneName))] <- Lipid_gene$GeneID[which(is.na(Lipid_gene$GeneName))]
#
Lipid_gene <- Lipid_gene[intersect(
  which(gsub("_","-",Lipid_gene$P..falciparum.ID)%in%rownames(Pfsce)),
  which(gsub("_","-",Lipid_gene$P..berghei.ID)%in%rownames(Pbsce))
  ),]
#
Lipid_gene$Gene.names[which(is.na(Lipid_gene$Gene.names))] <- Lipid_gene$P..falciparum.ID[which(is.na(Lipid_gene$Gene.names))]
```
##2.2. 表达矩阵
```{r}
pb_express<- AverageExpression(object = Pbsce,group.by = "Cluster")
pb_express <- pb_express$RNA
pb_express%<>%t()%>%scale()%>%t()
colnames(pb_express) <- c("ER","MR","ET","MT","LT","ES","MS","LS")

#
pf_express<- AverageExpression(object = Pfsce,group.by = "Scmap")
pf_express <- pf_express$RNA
pf_express%<>%t()%>%scale()%>%t()
colnames(pf_express) <- c("ER","MR","ET","MT","LT","ES","MS","LS")
#
pb_express <- pb_express[gsub("_","-",Lipid_gene$P..berghei.ID),]
rownames(pb_express) <- Lipid_gene$Gene.names
#
pf_express <- pf_express[gsub("_","-",Lipid_gene$P..falciparum.ID),]
rownames(pf_express) <- Lipid_gene$Gene.names
```
###2.3.
```{r,fig.height=12,fig.width=7}
p1 <- ComplexHeatmap::Heatmap(pf_express,
                              cluster_rows = T,cluster_columns = F,show_row_names = T,show_column_names = T,row_names_side = "left",
                              col=circlize::colorRamp2(c(-1, 0, 1), c("#2166AC", "white", "#B2182B")),
                              row_title = c("","","",""),
                              row_split = 4,
                              show_row_dend = F,
                              show_heatmap_legend = F,
                              column_title = "P. falciparum",
                              column_names_side = "top",column_names_rot = 45,clustering_method_rows = "complete",
                              border = T,border_gp = gpar(col = 'black', lwd = 2)
                              )  

p2 <-ComplexHeatmap::Heatmap(pb_express,
                             cluster_rows = T,cluster_columns = F,show_row_names = T,show_column_names = T,row_names_side = "left",
                              col=circlize::colorRamp2(c(-1, 0, 1), c("#2166AC", "white", "#B2182B")),
                             name = "Expression",
                             row_split =4,
                             column_title = "P. berghei",
                             column_names_side = "top",column_names_rot = 45,clustering_method_rows = "complete",
                             border = T,border_gp = gpar(col = 'black', lwd = 2)
                             )

p1+p2
```
