---
title: "Untitled"
author: "yangqingxin"
date: "2024/1/8"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#1 loading package and data
##1.1 package
```{r}
library(Seurat)
library(Matrix)
library(magrittr)
library(ggplot2)
library(data.table)
library(dplyr)
library(clusterProfiler)
library(org.Pf.plasmo.db)
library(rtracklayer)
library(xlsx)
library(RColorBrewer)
library(Mfuzz)
library(ggpubr)
library(cowplot)
```
##1.2 data
```{r}
Pbsce <- readRDS("../Data/01_01_Pb_seurat.Rds")
Pfsce <- readRDS("../Data/01_02_Pf_seurat.Rds")
```
#2. Mfuzz
##2.1. Making expression data
```{r}
#
PB_cycle <- AverageExpression(Pbsce,group.by = "Cluster")
PB_cycle <- PB_cycle$RNA
PB_cycle <- PB_cycle[which(rowSums(PB_cycle)>0),]

#
PF_cycle <- AverageExpression(Pfsce,group.by = "Scmap")
PF_cycle <- PF_cycle$RNA
PF_cycle <- PF_cycle[which(rowSums(PF_cycle)>0),]
```
##2.2 Cluster gene
###2.2.1. Pb
```{r}
Pb_df <- new("ExpressionSet", exprs = PB_cycle)
Pb_df <- standardise(Pb_df)
m <- mestimate(Pb_df)
set.seed(100)
Pb_cl <- mfuzz(Pb_df, c = 8, m = m)
#
saveRDS(Pb_cl,"../Analysis/03_01_pb_cl.Rds")
saveRDS(Pb_df,"../Analysis/03_02_pb_df.Rds")
```
###2.2.2. Pf
```{r}
Pf_df <- new("ExpressionSet", exprs = PF_cycle)
Pf_df <- standardise(Pf_df)
m <- mestimate(Pf_df)
set.seed(1234)
Pf_cl <- mfuzz(Pf_df, c = 8, m = m)
saveRDS(Pf_cl,"../Analysis/03_04_pf_cl.Rds")
saveRDS(Pf_df,"../Analysis/03_05_pf_df.Rds")
```
##2.3. Organize Mfuzz results
###2.3.1. Function
```{r}
Make_mfuzz_data <- function(cl,df){
  cluster_DT <- data.table(Cluster=cl$cluster%>%as.character(),Gene_name=cl$cluster%>%names%>%as.character())
  setkey(cluster_DT,Gene_name)
  plot_data <- df@assayData$exprs%>%as.data.frame()
  plot_data$Gene_name <- rownames(plot_data)
  plot_data%<>%as.data.table()
  plot_data <- melt(plot_data,id.vars=c("Gene_name"))
  setnames(plot_data,old = c("variable","value"),new = c("Time","Expression"))
  plot_data$Cluster <- cluster_DT[plot_data$Gene_name]$Cluster
  membership_DT <- cl$membership%>%as.data.frame()
  cluster <- cl$cluster%>%as.numeric()
  extract_mem <- function(x,y){
    z <- membership_DT[x,y]%>%as.numeric()
    return(z)
  }
  membership <-  mapply(extract_mem,c(1:length(cluster)),cluster)
  membership_DT <- data.table(Gene_name=rownames(membership_DT),Membership=membership)
  setkey(membership_DT,Gene_name)
    
  plot_data$Membership <- membership_DT[plot_data$Gene_name]$Membership
  plot_data%<>%as.data.table()
  return(plot_data)
}
```
###2.3.2. 
```{r}
#
Mfuzz_pb <- Make_mfuzz_data(cl=Pb_cl,df=Pb_df)
setorder(Mfuzz_pb,Gene_name)
Mfuzz_pb$color <- rep("grey",nrow(Mfuzz_pb))
Mfuzz_pb[Membership>0.95]$color <- "red"

#
Mfuzz_pf <- Make_mfuzz_data(cl=Pf_cl,df=Pf_df)
setorder(Mfuzz_pf,Gene_name)
Mfuzz_pf$color <- rep("grey",nrow(Mfuzz_pf))
Mfuzz_pf[Membership>0.95]$color <- "red"
```
##2.4. 
```{r,fig.width=18,fig.height=8}
#
p1 <- ggplot(Mfuzz_pb,aes(x=Time,y=Expression))+geom_line(aes(group=Gene_name,color=color),alpha=.4)+
  theme_classic2()+theme(legend.position = "none")+xlab("")+
  scale_x_discrete(expand = c(0.1,0))+scale_color_manual(values = c("grey","#F08080"))+
  facet_wrap(.~Cluster ,ncol = 4,labeller = )+  
  theme(axis.text.x = element_text(angle = 45,vjust = .9,hjust = .9))+
  theme(axis.text.x = element_text(size=20))+
  theme(strip.text = element_text(size=25))+
  theme(axis.text.y = element_text(size=15),axis.title.y = element_text(size=25))+
  ggtitle("P. berghei")+theme(plot.title = element_text(hjust=.5,size=30,face = "italic"))
#
p2 <- ggplot(Mfuzz_pf,aes(x=Time,y=Expression))+geom_line(aes(group=Gene_name,color=color),alpha=.4)+
  theme_classic2()+theme(legend.position = "none")+xlab("")+
  scale_x_discrete(expand = c(0.1,0))+scale_color_manual(values = c("grey","#F08080"))+
  facet_wrap(.~Cluster ,ncol = 4,labeller = )+  
  theme(axis.text.x = element_text(angle = 45,vjust = .9,hjust = .9))+
  theme(axis.text.x = element_text(size=20))+
  theme(strip.text = element_text(size=25))+
  theme(axis.text.y = element_text(size=15),axis.title.y = element_text(size=25))+
  ggtitle("P. falciparum")+theme(plot.title = element_text(hjust=.5,size=30,face = "italic"))
p1
p2
```

#3. Enrich analysis
##3.1.
```{r}
ID_transform <- read.xlsx("../Data/02_Gene_Orth_Data.xlsx",sheetIndex = 1)%>%as.data.table()
```
##3.2. select Mid- Late— troph stage genes
```{r}
#
Pbgene <- c(Mfuzz_pb[Cluster==1&Membership>0.95]$Gene_name%>%unique(),
            Mfuzz_pb[Cluster==8&Membership>0.95]$Gene_name%>%unique()
          )
Pbgene <- gsub("-","_",Pbgene)
#
setkey(ID_transform,berghei)
DF <- data.table(
  Pf_gene=ID_transform[Pbgene]$falciparum,
  Pb_gene=Pbgene
)
saveRDS(DF,"../Analysis/03_03_pb_Mfuzzgene.Rds")
#
Pfgene <- c(Mfuzz_pf[Cluster==6&Membership>0.95]$Gene_name%>%unique(),
            Mfuzz_pf[Cluster==1&Membership>0.95]$Gene_name%>%unique()
          )
Pfgene <- gsub("-","_",Pfgene)
setkey(ID_transform,falciparum)
DF <- data.table(
  Pf_gene=Pfgene,
  Pb_gene=ID_transform[Pfgene]$berghei
)
saveRDS(DF,"../Analysis/03_06_pf_Mfuzzgene.Rds")
```
##3.3. Transform GeneID
```{r}
setkey(ID_transform,berghei)
Pbgene <- ID_transform[Pbgene]$falciparum
Pbgene <- subset(Pbgene,!is.na(Pbgene))

gc <- list(Pf=Pfgene,Pb=Pbgene)
```
##3.4. GO(BP)
```{r,fig.height=10,fig.width=8}
#
Go_BP <- compareCluster(gc,
                     fun="enrichGO", 
                     OrgDb='org.Pf.plasmo.db',
                     keyType = "SYMBOL",     
                     ont= "BP")
dotplot(Go_BP, showCategory=6,font.size=10, includeAll=T)
```
##3.5. KEGG
```{r,fig.width=7,fig.height=5}
KEGG <- compareCluster(geneCluster = gc,fun = "enrichKEGG",organism="pfa")
dotplot(KEGG, showCategory=6,font.size=8, includeAll=T)+theme(axis.text.y =  element_text(size=12),axis.text.x = element_text(size=13))
```





