---
title: "Untitled"
author: "yangqingxin"
date: "2024/4/13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#1.
##1.1.
```{r}
library(data.table)
library(dplyr)
library(tidyr)
library(magrittr)
library(randomForest)
library(caret)
library(ROSE)
library(pROC)
library(PRROC)
library(rtracklayer)
library(modEvA)
library(ggrepel)
```
##1.2.特征的筛选
```{r}
#
Feature <- readRDS("../Data/04_RF_GeneInfo.Rds")%>%as.data.table()
#
Feature_unkonwn <- Feature %>% filter(Label == 2)
Feature_unkonwn$Label%<>%as.character()
Feature_konwn <- Feature %>% filter(Label != 2)
Feature_konwn$Label%<>%as.character()
Feature_konwn$Label <- factor(Feature_konwn$Label,levels = c(0,1))
```
##1.3. balance
```{r}
positive_samples <- Feature_konwn %>% filter(Label == 1)
negative_samples <- Feature_konwn %>% filter(Label == 0)

set.seed(123)
if (nrow(positive_samples) < 100) {
  positive_samples_oversampled <- positive_samples[sample(1:nrow(positive_samples), 100, replace = TRUE), ]
} else {
  positive_samples_oversampled <- positive_samples
}
set.seed(123)
if (nrow(negative_samples) > 100) {
  negative_samples_undersampled <- negative_samples[sample(1:nrow(negative_samples), 100,replace = TRUE), ]
} else {
  negative_samples_undersampled <- negative_samples
}
balanced_data <- rbind(positive_samples_oversampled, negative_samples_undersampled)
```
#2.
##2.1.
```{r}
set.seed(123)
folds <-createMultiFolds(y=balanced_data$Label,k=10,times=1)
```
##2.2.
```{r,warning=FALSE}
AUROC_Plot <- lapply(c(1:10),function(x){
  train<- balanced_data[ folds[[x]],] 
  test <- balanced_data[-folds[[x]],] 
  set.seed(123)
  rfModel <- randomForest(Label ~ . - GeneID, data = train, importance = TRUE,proximity = TRUE,ntree = 500)
  model_pre <- predict(rfModel, test,type = "prob")
  model_pre <- model_pre[,2]
  #
  roc_obj <- AUC(obs=test$Label,pred=model_pre,curve = "ROC", simplif=FALSE,plot = FALSE)
  Data <- roc_obj$thresholds
  Data$Time <- x
  Data$AUC <- roc_obj$AUC
  return(Data)
}
)
AUROC_Plot <- do.call(rbind,AUROC_Plot)


AUPRC_Plot <- lapply(c(1:10),function(x){
  train<- balanced_data[ folds[[x]],] 
  test <- balanced_data[-folds[[x]],] 
  set.seed(123)
  rfModel <- randomForest(Label ~ . - GeneID, data = train, importance = TRUE,proximity = TRUE,ntree = 500)
  model_pre <- predict(rfModel, test,type = "prob")
  model_pre <- model_pre[,2]
  #
  aupr <- AUC(obs=test$Label,pred=model_pre,curve = "PR", simplif=FALSE,plot = FALSE)
  Data <- aupr$thresholds
  Data$Time <- x
  Data$PR <- aupr$AUC
  return(Data)
}
)
AUPRC_Plot <- do.call(rbind,AUPRC_Plot)

Gini_Plot <- lapply(c(1:10),function(x){
  train<- balanced_data[ folds[[x]],] 
  test <- balanced_data[-folds[[x]],] 
  set.seed(123)
  rfModel <- randomForest(Label ~ . - GeneID, data = train, importance = TRUE,proximity = TRUE,ntree = 500)
  Ginivalue <- importance(rfModel)[,4]
  Gini <- data.table(Feature= Ginivalue%>%names(),
                     Ginivalue = Ginivalue%>%as.numeric()
                     )
  Gini$Time <- x
  return(Gini)
}
)
Gini_Plot <- do.call(rbind,Gini_Plot)
```
#3. 
##3.1.
```{r,fig.width=5,fig.height=5}
Gini_Plot <- Gini_Plot[,.(Gini=mean(Ginivalue)),by=.(Feature)]
setorder(Gini_Plot,Gini)
Gini_Plot$Feature <- factor(Gini_Plot$Feature,levels = Gini_Plot$Feature)
#
ggplot(Gini_Plot,aes(x=Gini,y=Feature))+geom_point(size=3)+theme_bw()+
  ggtitle("Mean Decrease Gini")+xlab("")+ylab("")+
  theme(axis.text = element_text(size = 12),axis.title = element_text(size = 15),
        plot.title = element_text(size = 20,hjust = 0.5)
        )+guides(color=FALSE)
```
##3.2. 
```{r}
AUROC_Plot$Time%<>%as.character()
AUROC_Plot%<>%as.data.table()
AUROC_Plot_new <- AUROC_Plot[,.(specificity=mean(specificity),sensitivity=mean(sensitivity)),by=.(thresholds)]
AUROC_Plot_new$Time <- "Mean"
AUROC_Plot_new <- rbind(AUROC_Plot_new,AUROC_Plot[,c("thresholds","specificity","sensitivity","Time")])
AUROC_Plot_new$Time <- factor(AUROC_Plot_new$Time,levels = c("Mean","1","2","3","4","5","6","7","8","9","10"))
#
ggplot(AUROC_Plot_new,aes(x=1-specificity,y=sensitivity))+geom_line(alpha=.8,size=.5,aes(group=Time,color=Time))+theme_bw()+
  geom_segment(aes(x = 0, y = 0, xend = 1, yend = 1), colour = "grey",linetype=2)+
  scale_color_manual(values = c("red","grey","grey","grey","grey","grey","grey","grey","grey","grey","grey"))+
  ggtitle("AUROC")+guides(color=FALSE)+
  theme(axis.text = element_text(size = 12),axis.title = element_text(size = 15),
        plot.title = element_text(size = 20,hjust = 0.5)
        )+coord_fixed(ratio = .9)+
  annotate(geom = "text",label=paste0("Mean of AUROC: ",round(mean(AUROC_Plot$AUC),digits = 2)),x=.65,y=.15,size=5)
```

##3.3. 
```{r}
AUPRC_Plot$Time%<>%as.character()
AUPRC_Plot%<>%as.data.table()
AUPRC_Plot_new <- AUPRC_Plot[,.(sensitivity=mean(sensitivity),precision=mean(precision)),by=.(thresholds)]
AUPRC_Plot_new$Time <- "Mean"
AUPRC_Plot_new <- rbind(AUPRC_Plot_new,AUPRC_Plot[,c("thresholds","sensitivity","precision","Time")])
AUPRC_Plot_new$Time <- factor(AUPRC_Plot_new$Time,levels =  c("Mean","1","2","3","4","5","6","7","8","9","10"))
#
ggplot(AUPRC_Plot_new,aes(x=sensitivity,y=precision))+geom_line(alpha=.8,size=.5,aes(group=Time,color=Time))+theme_bw()+
  geom_segment(aes(x = 0, y = 1, xend = 1, yend = 0), colour = "grey",linetype=2)+
  scale_color_manual(values = c("red","grey","grey","grey","grey","grey","grey","grey","grey","grey","grey"))+
  ggtitle("AUPRC")+guides(color=FALSE)+
  theme(axis.text = element_text(size = 12),axis.title = element_text(size = 15),
        plot.title = element_text(size = 20,hjust = 0.5)
        )+coord_fixed(ratio = .9)+
 annotate(geom = "text",label=paste0("Mean of AUPRC: ",round(mean(AUPRC_Plot$PR),digits = 2)),x=.3,y=.15,size=5)+xlab("Recall")
```
##3.4. 
```{r}
AUROC_res <- AUROC_Plot[,c("Time","AUC")]%>%unique()
AUPRC_res  <- AUPRC_Plot[,c("Time","PR")]%>%unique()
```

#4.
##4.1. 
```{r}
#
MRS <- lapply(c(1:10),function(x){
  train<- balanced_data[folds[[x]],] 
  set.seed(123)
  rfModel <- randomForest(Label ~ . - GeneID, data = train, importance = TRUE,proximity = TRUE,ntree = 500)
  model_pre <- predict(rfModel, Feature_unkonwn,type = "prob")
  model_pre <- model_pre[,2]
  DF <- data.table(
    GeneID = Feature_unkonwn$GeneID,
    Value = model_pre,
    Time=rep(x,nrow(Feature_unkonwn))
  )
    return(DF)
}
)
#
MRS <- do.call(rbind,MRS)
MRS <- MRS[,.(value=mean(Value)),by=.(GeneID)]
MRS%<>%as.data.table()
setkey(MRS,GeneID)
```
##4.2. 
```{r}
Pf_gene_ori <- readRDS("../Analysis/03_06_pf_Mfuzzgene.Rds")
Pb_gene_ori <- readRDS("../Analysis/03_03_pb_Mfuzzgene.Rds")
#
Gene <- Reduce(intersect,list(
  Troph_pf = subset(Pf_gene_ori$Pf_gene,!is.na(Pf_gene_ori$Pf_gene))
  ,Troph_pb = subset(Pb_gene_ori$Pf_gene,!is.na(Pb_gene_ori$Pf_gene))
  )
  )
```
##4.4. 
```{r}
MRS <- MRS[Gene]
MRS <- MRS[-which(is.na(MRS$value)),]
setorder(MRS,-value)
saveRDS(MRS,"../Data/ConservedGene_MRS.Rds")
```







